- name: Installing Neutron and its components
  apt:
    name:
      - neutron-openvswitch-agent
      - neutron-linuxbridge-agent
      - neutron-server
      - python3-neutronclient
      - python3-neutron
    state: present

- name: Configuring RabbitMQ message queue access
  copy:
    dest: /etc/neutron/neutron.conf
    content: |
              [DEFAULT]
              transport_url = rabbit://openstack:1234@controller
- name: Configuring Identity service access
  copy:
    dest: /etc/neutron/neutron.conf
    content: |
              [DEFAULT]
              auth_strategy = keystone
              [keystone_authtoken]
              www_authenticate_uri = http://controller:5000
              auth_url = http://controller:5000
              memcached_servers = controller:11211
              auth_type = password
              project_domain_name = default
              user_domain_name = default
              project_name = service
              username = neutron
              password = 1234

- name: Configuring the lock path
  copy:
    dest: /etc/neutron/neutron.conf
    content: |
              [oslo_currency]
              lock_path = /var/lib/neutron/tmp

- name: Configuring the access parameters
  copy:
    dest: /etc/nova/nova.conf
    content: |
              [neutron]
              auth_url = http://controller:5000
              auth_type = password
              project_domain_name = default
              user_domain_name = default
              region_name = RegionOne
              project_name = service
              username = neutron
              password = 1234

- name: Restarting Compute Service
  service:
    name: nova-compute
    state: restarted

- name: Restarting Linux Bridge Agent
  service:
    name: neutron-linuxbridge-agent
    state: restarted
